### PR TITLE
remove FileStreamAsyncKafkaEnvironment in favor of manual wrapping of…

### PR DESCRIPTION
**Pull request by matt-bernstein**
… base class

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/3f72b4b3a4e45b76752ca25be74a6dc1cab24e3c is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/1fd4b96a685ee5ad130a7ee1fdce2d8edd4fcc0f is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/5503204cc781d2f67ba1733527ce6bb8a0e6cd89 is created.

**Review by pakelley — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/e8ddba25288b8f42d4a487c11abcd26f8385f55a is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/3ce8b4f7033d82fd9f3280f6e6247ef0af0dddea is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/76c9c5139ef8cbadc6fe385fddc3cc9a644c57f1 is created.

**Pull request merged**
