### PR TITLE
fix: dia-1108 : adding fix to ensure all messages left in output topic are sent to lse and no predictions are lost

### PR DESCRIPTION
**Pull request by forum-hs**

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/cd9ac3dc789d0d439bae34d9a9b8dd275e9500e1 is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/bc17088b3a6ffb6bb4ffc6bc94da3c0e56fa319f is created.

**Review by hakan458 — APPROVED** [review]

**Review by matt-bernstein — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/ed56479d5497a922c758d0eb4e17c0d0a89ca606 is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/4f4ca468db56017c18d286ca94c82f21d3b2019d is created.

**Pull request merged**
