### PR TITLE
Running agent.arun(input=df) with environment=None is totally valid.

### PR DESCRIPTION
**Pull request by chemeris**
Otherwise this code requires us to create an dummy async environment which is not used in the code and not even possible with the current code base.

### CODE REVIEW

**Review by niklub — APPROVED** [review]
Thanks for the fix. Although I totally agree with your proposal, it is still interesting how do you specifically use async call without async environment? It would be great if you could provide an example code so we would incorporate it in our future tutorials

**Comment by chemeris** [comment]
Thank you, and I look forward to having this merged.

I can't provide an example code, unfortunately, but the code we're writing is based on the `classification_skill.ipynb` example. We simply changed the synchronous `agent.run()` to asynchronous `await agent.arun()`. 

Two reasons for this:
1. We're running in async FastAPI handler anyway, so why not?
2. The async agent supports setting `temperature=0`, while sync one doesn't. And given the default temperature is AFAIK set to 1, it reduces reliability of the classification. And in general it looked like sync code is pretty much abandoned in favor for the new async one.

That said, I always thought that an `environment` is only needed during "teaching". Are you saying there are other use cases for it during normal production operation? The documentation is not very detailed on this part.

**Comment by chemeris** [comment]
Hi, is there anything else required to merge this PR?

**Comment by chemeris** [comment]
@niklub Please, could you merge this PR?
I see that the change is approved but it's still says "This workflow requires approval from a maintainer"

**Comment by chemeris** [comment]
Any news?

**Comment by chemeris** [comment]
Hi, ping about this PR - it's really simple

**Comment by chemeris** [comment]
@niklub @matt-bernstein Any chance this can be merged?
It's a really simple one and @niklub has approved, but someone with write access to the repo has to click the button to merge.

**Comment by matt-bernstein** [comment]
Thanks for the nudge here. Appreciate not letting this one fall through the cracks. :slightly_smiling_face:

**Pull request merged**
