### PR TITLE
fix: dia-1330: Adding log messages to capture message into and out of kafka topic. 

### PR DESCRIPTION
**Pull request by forum-hs**

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/69da387a9ad4ff1b898547b7369e578c11f4a3fd is created.

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/9fd41a2db25276dbf91b881b235d2ff2c2fd9a80 is created.

**Review by farioas — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/af6b60bde4b1703bc020ebc3e5ac274ad97e48c2 is created.

**Review by matt-bernstein — APPROVED** [review]

**Review by hakan458 — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
Commit https://github.com/HumanSignal/infra/commit/349cd572374afb1967f3a5800797ac12665a6da8 is created.

**Pull request merged**
